### ISSUE TITLE
Unhandled exception for Rcon

### ISSUE THREAD

**Issue by Firav** [rfalias/project_zomboid_bot#30]
Whenever the server is offline, the rcon utility has a fit.

```
Traceback (most recent call last):
  File "/servers/dbots/project_zomboid_bot-main/SourceRcon.py", line 81, in connect
    self.tcp.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pzbot.py", line 647, in status_task
    playercount = await pzplayers()
  File "pzbot.py", line 639, in pzplayers
    c_run = await rcon_command(None, ["players"])
  File "pzbot.py", line 250, in rcon_command
    r = sr.rcon(" ".join(command))
  File "/servers/dbots/project_zomboid_bot-main/SourceRcon.py", line 215, in rcon
    self.connect()
  File "/servers/dbots/project_zomboid_bot-main/SourceRcon.py", line 83, in connect
    raise SourceRconError('Disconnected from RCON, please restart program to continue.')
SourceRcon.SourceRconError: Disconnected from RCON, please restart program to continue.
```

**Comment by rfalias** [comment]
Fixed in #31

**Comment by rfalias** [comment]
Thanks for finding this. The exception in the survivor watcher portion was killing all of the discord connections as well.

**Comment by Firav** [comment]
Thank you for the speedy fix!
